# Site Info
title: '개발 기록장'
tagline: 'Today I Learned'
description: 'TIL Github Blog'
baseurl: ""
url: https://1day1commit.github.io
# logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate

markdown: kramdown
kramdown:
  input: GFM
  syntax_highligther: rouge

excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
# paginate: 5
# paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: TAEYEONG JEONG
  description: 개발 공부 기록
  contact:
    # linkedin:  https://www.linkedin.com/
    github:    https://github.com/1day1commit
    # facebook:  https://www.facebook.com/
    # twitter:   https://twitter.com/
    email:    mailto:dev.taeyeong@gmail.com

# Navigation (2nd level links supported)
nav:
  전체 글:
  - '/all-post/'
  
  Categories:
    - '/'
    - { JavaScript: /categories/javascript }
    - { React: '/categories/react' }
    - { Node.js: '/categories/node'}
    - { Database: '/categories/database'}
    - { Git/GitHub: /categories/git-github }
    - { 알고리즘: /categories/algorithm }
    - { HTTP: /categories/http }
    - { HTML/CSS: /categories/html-css }
    - { WeCode: /categories/wecode }
    
  Tags:
    - '/tags/'
  About:
    - '/about/'
  Search:
    - /search/

# Where are tags and categories displayed
# tag_page: '/blog/tags/'
# category_page: '/blog/categories/'


# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: '' # leave blank if you don't want disqus


# Use the following plug-ins
gems:
  - jekyll-paginate

# 시간대 변경
timezone: Asia/Seoul