# Site Info
title: '개발 기록장'
tagline: '개발 공부 일지'
description: '공부한 것을 기록하는 공간'
baseurl: ""
url: https://1day1commit.github.io
# logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: TAEYEONG JEONG
  description: 
  contact:
    # linkedin:  https://www.linkedin.com/
    github:    https://github.com/1day1commit
    # facebook:  https://www.facebook.com/
    # twitter:   https://twitter.com/
    email:    mailto:dev.taeyeong@gmail.com

# Navigation (2nd level links supported)
nav:
  Categories:
    - '/'
    # - { Categories All: '/blog/categories/' }
    - { TIL (Today I Learned): '/blog/categories/#til' }
    - { 알고리즘: '/blog/categories/#알고리즘' }
  Tags:
    - '/blog/tags/'
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'


# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: '' # leave blank if you don't want disqus


# Use the following plug-ins
gems:
  - jekyll-paginate
